version: '3.9'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass1234
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db


