version: '3.9'
services:

  api:
    build: 
      dockerfile: Dockerfile
      context: ./backend

    restart: unless-stopped
    env_file: ./.env
    ports:
      - "$SERVER_PORT:5000"
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=pass1234
      - DB_NAME=test_db
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass1234
    volumes:
      - ./data:/var/lib/mysql:rw
      - ./db:/docker-entrypoint-initdb.d

  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db